### ISSUE TITLE
要怎么设置才能让查询的时候不自动加_

### ISSUE THREAD

**Issue by LuciferJun1227** [automvc/bee#8]
cardNo在查询的时候会显示card_no,要怎么设置才能不变化

**Comment by automvc** [comment]
是DB表字段与java命名转换还是打印日志的时候？

**Comment by automvc** [comment]
> cardNo在查询的时候会显示card_no,要怎么设置才能不变化

是DB表字段与java命名转换还是打印日志的时候？

**Comment by LuciferJun1227** [comment]
DB表字段与java命名的时候，就是数据库是cardNo，但是在java程序中查询的时候是card_no,然后出错了

**Comment by automvc** [comment]
默认实现了三种命名转换规则。
可以通过代码实现：
		 NameTranslate nameTranslat =new OriginalName();
//		 NameTranslate nameTranslat =new UnderScoreAndCamelName();
//		 NameTranslate nameTranslat =new UpperCaseUnderScoreAndCamelName();
		 HoneyFactory f=BeeFactory.getHoneyFactory();
		 f.setNameTranslate(nameTranslat);
		 Suid suid=f.getSuid();
也可以通过配置：
#since 1.7.2
#default translate type. 1 : order_no<-->orderNo(DB<-->Java), 2: ORDER_NO<-->orderNo(DB<-->Java), 3: original
#if want to use other naming rule, you can define a new class implements NameTranslate
bee.osql.naming.translate.type=3

请下载最新代码即可。 maven依赖，等候1.7.2更新提交。

**Comment by automvc** [comment]
> DB表字段与java命名的时候，就是数据库是cardNo，但是在java程序中查询的时候是card_no,然后出错了

请获取最新的版本依赖：
		<dependency>
			<groupId>org.teasoft</groupId>
			<artifactId>bee</artifactId>
			<version>1.7.2</version>
		</dependency>

		<dependency>
			<groupId>org.teasoft</groupId>
			<artifactId>honey</artifactId>
			<version>1.7.2</version>
		</dependency>
